JCasC:
  openshiftClouds:
    dev:
      serverUrl: "https://api.cs2-dev.nz.service.test:6443"
      credentialsId: "cs2-dev-openshift"
    prod:
      serverUrl: "https://api.cs2.nz.service.anz:6443"
      credentialsId: "cs2-prod-openshift"
