JCasC:
  quietDown:
    # cs1 cluster contains the backup instance, in quiet down mode by default
    quietDown: true

  openshiftClouds:
    dev:
      serverUrl: "https://api.cs1-dev.nz.service.test:6443"
      credentialsId: "cs1-dev-openshift"
    prod:
      serverUrl: "https://api.cs1.nz.service.anz:6443"
      credentialsId: "cs1-prod-openshift"
