JCasC:
  vault:
    credentials:
      # OpenShift credentials
      dev-openshift-credential:
        kind: vaultStringCredentialImpl
        description: The 'jenkins' service account JWT from dev for Kubernetes plugin
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: dev-openshift-credential
      cs1-prod-openshift: # to be loaded to vault
        kind: vaultStringCredentialImpl
        description: "The 'jenkins' service account JWT from OCP4 cs1-prod for Kubernetes plugin"
        path: "secret/context/ib-ci/jenkins/keys"
        scope: GLOBAL
        vaultKey: "cs1-prod-openshift"
      cs2-prod-openshift: # to be loaded to vault
        kind: vaultStringCredentialImpl
        description: "The 'jenkins' service account JWT from OCP4 cs2-prod for Kubernetes plugin"
        path: "secret/context/ib-ci/jenkins/keys"
        scope: GLOBAL
        vaultKey: "cs2-prod-openshift"

      # Slack integration
      IBSlackIntegration:
        kind: vaultStringCredentialImpl
        description: Token for Slack integration
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: IBSlackIntegration

      # DriveTrain tokens
      pipeline-ib-bearer-token:
        kind: vaultStringCredentialImpl
        description: Token for IB DriveTrain integration
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: pipeline-ib-bearer-token
      pipeline-ib-synthetic-monitor-bearer-token:
        kind: vaultStringCredentialImpl
        description: Token for IB Synthetic Monitor DriveTrain integration
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: pipeline-ib-synthetic-monitor-bearer-token

      # Credentials for IB/PreAuth automation tests
      proxy-credentials:
        kind: vaultUsernamePasswordCredentialImpl
        description: Service account to access the corporate proxy
        path: secret/context/ib-ci/jenkins/pairs/proxy-credentials
        scope: GLOBAL
      production-bvt-credentials:
        kind: vaultUsernamePasswordCredentialImpl
        description: Production BVT Customer RM and Password
        path: secret/context/ib-ci/jenkins/pairs/production-bvt-credentials
        scope: GLOBAL
      production-g3-api-key:
        kind: vaultStringCredentialImpl
        description: Production G3 API Key
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: production-g3-api-key

      # Deployment secrets for IB
      ACCPT1_IB_SERVER_SSH_KEY:
        kind: vaultSSHUserPrivateKeyImpl
        description: Credentials login into ACCPT1 WebSphere environment.
        path: secret/context/ib-ci/jenkins/pairs/ACCPT1_IB_SERVER_SSH_KEY
        scope: GLOBAL
      ACCPT1_IB_PUBLIC_DB_CREDENTIALS:
        kind: vaultUsernamePasswordCredentialImpl
        description: IB Database credential for DB migration
        path: secret/context/ib-ci/jenkins/pairs/ACCPT1_IB_PUBLIC_DB_CREDENTIALS
        scope: GLOBAL
      ACCPT1_IB_PUBLIC_ENCRYPTION_KEY:
        kind: vaultStringCredentialImpl
        description: IB Security Encryption Key
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: ACCPT1_IB_PUBLIC_ENCRYPTION_KEY
      UNION1_IB_SERVER_SSH_KEY:
        kind: vaultSSHUserPrivateKeyImpl
        description: Credentials login into UNION1 WebSphere environment.
        path: secret/context/ib-ci/jenkins/pairs/UNION1_IB_SERVER_SSH_KEY
        scope: GLOBAL
      UNION1_IB_PUBLIC_DB_CREDENTIALS:
        kind: vaultUsernamePasswordCredentialImpl
        description: IB Database credential for DB migration
        path: secret/context/ib-ci/jenkins/pairs/UNION1_IB_PUBLIC_DB_CREDENTIALS
        scope: GLOBAL
      UNION1_IB_PUBLIC_ENCRYPTION_KEY:
        kind: vaultStringCredentialImpl
        description: IB Security Encryption Key
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: UNION1_IB_PUBLIC_ENCRYPTION_KEY
      REHEARSAL1_IB_SERVER_SSH_KEY:
        kind: vaultSSHUserPrivateKeyImpl
        description: Credentials login into REHEARSAL1 WebSphere environment.
        path: secret/context/ib-ci/jenkins/pairs/REHEARSAL1_IB_SERVER_SSH_KEY
        scope: GLOBAL
      REHEARSAL1_IB_PUBLIC_DB_CREDENTIALS:
        kind: vaultUsernamePasswordCredentialImpl
        description: IB Database credential for DB migration
        path: secret/context/ib-ci/jenkins/pairs/REHEARSAL1_IB_PUBLIC_DB_CREDENTIALS
        scope: GLOBAL
      REHEARSAL1_IB_PUBLIC_ENCRYPTION_KEY:
        kind: vaultStringCredentialImpl
        description: IB Security Encryption Key
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: REHEARSAL1_IB_PUBLIC_ENCRYPTION_KEY
      PROD_IB_SERVER_SSH_KEY:
        kind: vaultSSHUserPrivateKeyImpl
        description: Credentials login into PROD WebSphere environment.
        path: secret/context/ib-ci/jenkins/pairs/PROD_IB_SERVER_SSH_KEY
        scope: GLOBAL
      PROD_IB_PUBLIC_DB_CREDENTIALS:
        kind: vaultUsernamePasswordCredentialImpl
        description: IB Database credential for DB migration
        path: secret/context/ib-ci/jenkins/pairs/PROD_IB_PUBLIC_DB_CREDENTIALS
        scope: GLOBAL
      PROD_IB_PUBLIC_ENCRYPTION_KEY:
        kind: vaultStringCredentialImpl
        description: IB Security Encryption Key
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: PROD_IB_PUBLIC_ENCRYPTION_KEY

      # Deployment secrets for IBAT
      ACCPT1_IBAT_CUSTOMER_CREDENTIALS_FILE:
        kind: vaultStringCredentialImpl
        description: IBAT Customer Database and Keystore credentials for ACCPT1
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: ACCPT1_IBAT_CUSTOMER_CREDENTIALS_FILE
      ACCPT1_IBAT_SYSADMIN_CREDENTIALS_FILE:
        kind: vaultStringCredentialImpl
        description: IBAT SysAdmin Database and Keystore credentials for ACCPT1
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: ACCPT1_IBAT_SYSADMIN_CREDENTIALS_FILE
      ACCPT1_IBAT_CUSTOMER_KEYTAB_FILE_BASE64:
        kind: vaultStringCredentialImpl
        description: SPNEGO Kerberos Keytab for IBAT Customer for ACCPT1
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: ACCPT1_IBAT_CUSTOMER_KEYTAB_FILE_BASE64
      ACCPT1_IBAT_SYSADMIN_KEYTAB_FILE_BASE64:
        kind: vaultStringCredentialImpl
        description: SPNEGO Kerberos Keytab for IBAT SysAdmin for ACCPT1
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: ACCPT1_IBAT_SYSADMIN_KEYTAB_FILE_BASE64
      ACCPT1_IBAT_LOGIN_JOURNEY:
        kind: vaultUsernamePasswordCredentialImpl
        description: Ibat journey tests user credentials for ACCPT1
        path: secret/context/ib-ci/jenkins/pairs/ACCPT1_IBAT_LOGIN_JOURNEY
        scope: GLOBAL
      UNION1_IBAT_CUSTOMER_CREDENTIALS_FILE:
        kind: vaultStringCredentialImpl
        description: IBAT Customer Database and Keystore credentials for UNION1
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: UNION1_IBAT_CUSTOMER_CREDENTIALS_FILE
      UNION1_IBAT_SYSADMIN_CREDENTIALS_FILE:
        kind: vaultStringCredentialImpl
        description: IBAT SysAdmin Database and Keystore credentials for UNION1
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: UNION1_IBAT_SYSADMIN_CREDENTIALS_FILE
      UNION1_IBAT_CUSTOMER_KEYTAB_FILE_BASE64:
        kind: vaultStringCredentialImpl
        description: SPNEGO Kerberos Keytab for IBAT Customer for UNION1
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: UNION1_IBAT_CUSTOMER_KEYTAB_FILE_BASE64
      UNION1_IBAT_SYSADMIN_KEYTAB_FILE_BASE64:
        kind: vaultStringCredentialImpl
        description: SPNEGO Kerberos Keytab for IBAT SysAdmin for UNION1
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: UNION1_IBAT_SYSADMIN_KEYTAB_FILE_BASE64
      UNION1_IBAT_LOGIN_JOURNEY:
        kind: vaultUsernamePasswordCredentialImpl
        description: Ibat journey tests user credentials for UNION1
        path: secret/context/ib-ci/jenkins/pairs/UNION1_IBAT_LOGIN_JOURNEY
        scope: GLOBAL
      REHEARSAL1_IBAT_CUSTOMER_CREDENTIALS_FILE:
        kind: vaultStringCredentialImpl
        description: IBAT Customer Database and Keystore credentials for REHEARSAL1
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: REHEARSAL1_IBAT_CUSTOMER_CREDENTIALS_FILE
      REHEARSAL1_IBAT_SYSADMIN_CREDENTIALS_FILE:
        kind: vaultStringCredentialImpl
        description: IBAT SysAdmin Database and Keystore credentials for REHEARSAL1
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: REHEARSAL1_IBAT_SYSADMIN_CREDENTIALS_FILE
      REHEARSAL1_IBAT_CUSTOMER_KEYTAB_FILE_BASE64:
        kind: vaultStringCredentialImpl
        description: SPNEGO Kerberos Keytab for IBAT Customer for REHEARSAL1
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: REHEARSAL1_IBAT_CUSTOMER_KEYTAB_FILE_BASE64
      REHEARSAL1_IBAT_SYSADMIN_KEYTAB_FILE_BASE64:
        kind: vaultStringCredentialImpl
        description: SPNEGO Kerberos Keytab for IBAT SysAdmin for REHEARSAL1
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: REHEARSAL1_IBAT_SYSADMIN_KEYTAB_FILE_BASE64
      REHEARSAL1_IBAT_LOGIN_JOURNEY:
        kind: vaultUsernamePasswordCredentialImpl
        description: Ibat journey tests user credentials for REHEARSAL1
        path: secret/context/ib-ci/jenkins/pairs/REHEARSAL1_IBAT_LOGIN_JOURNEY
        scope: GLOBAL
      PROD_IBAT_CUSTOMER_CREDENTIALS_FILE:
        kind: vaultStringCredentialImpl
        description: IBAT Customer Database and Keystore credentials for PROD
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: PROD_IBAT_CUSTOMER_CREDENTIALS_FILE
      PROD_IBAT_SYSADMIN_CREDENTIALS_FILE:
        kind: vaultStringCredentialImpl
        description: IBAT SysAdmin Database and Keystore credentials for PROD
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: PROD_IBAT_SYSADMIN_CREDENTIALS_FILE
      PROD_IBAT_CUSTOMER_KEYTAB_FILE_BASE64:
        kind: vaultStringCredentialImpl
        description: SPNEGO Kerberos Keytab for IBAT Customer for PROD
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: PROD_IBAT_CUSTOMER_KEYTAB_FILE_BASE64
      PROD_IBAT_SYSADMIN_KEYTAB_FILE_BASE64:
        kind: vaultStringCredentialImpl
        description: SPNEGO Kerberos Keytab for IBAT SysAdmin for PROD
        path: secret/context/ib-ci/jenkins/keys
        scope: GLOBAL
        vaultKey: PROD_IBAT_SYSADMIN_KEYTAB_FILE_BASE64
