templates:
  - config-jcasc.yaml
tests:
  - it: should include bitbucket config in default config scripts when configured
    set:
      JCasC:
        defaultConfig: true
        anzBitbucket:
          enabled: true
          manageHooks: true
          credentialsId: "anz-bitbucket-cred"
    asserts:
      - isNotNull:
          path: data.[jcasc-default-config-bitbucket.yaml]
      - matchSnapshot:
          path: data.[jcasc-default-config-bitbucket.yaml]
  - it: should ignore credential id when manage hooks disabled
    set:
      JCasC:
        defaultConfig: true
        anzBitbucket:
          enabled: true
          manageHooks: false
          credentialsId: "anz-bitbucket-cred"
    asserts:
      - isNotNull:
          path: data.[jcasc-default-config-bitbucket.yaml]
      - matchSnapshot:
          path: data.[jcasc-default-config-bitbucket.yaml]
  - it: should include blank bitbucket config in default config scripts when not configured
    set:
      JCasC:
        defaultConfig: true
    asserts:
      - isNotNull:
          path: data.[jcasc-default-config-bitbucket.yaml]
      - matchSnapshot:
          path: data.[jcasc-default-config-bitbucket.yaml]
  - it: should not include bitbucket config in default config scripts when there is custom config script for the section
    set:
      JCasC:
        defaultConfig: true
        configScripts:
          custom-override: |
            unclassified:
              bitbucketEndpointConfiguration:
                endpoints: []
    asserts:
      - isNull:
          path: data.[jcasc-default-config-bitbucket.yaml]
      - isNotNull:
          path: data.[custom-override.yaml]
