templates:
  - config-jcasc.yaml
tests:
  - it: should include proxy config in default config scripts when configured
    set:
      JCasC:
        defaultConfig: true
        master:
          proxy:
            name: "10.1.1.1"
            port: 80
            noProxyHost: |-
              *.service.dev
    asserts:
      - isNotNull:
          path: data.[jcasc-default-config-proxy.yaml]
      - matchSnapshot:
          path: data.[jcasc-default-config-proxy.yaml]
  - it: should include blank proxy config in default config scripts when not configured
    set:
      JCasC:
        defaultConfig: true
    asserts:
      - isNotNull:
          path: data.[jcasc-default-config-proxy.yaml]
      - matchSnapshot:
          path: data.[jcasc-default-config-proxy.yaml]
  - it: should not include proxy config in default config scripts when there is custom config script for the section
    set:
      JCasC:
        defaultConfig: true
        configScripts:
          custom-override: |
            jenkins:
              proxy:
                name: 10.1.1.10
    asserts:
      - isNull:
          path: data.[jcasc-default-config-proxy.yaml]
      - isNotNull:
          path: data.[custom-override.yaml]
