templates:
  - config-jcasc.yaml
tests:
  - it: should include quiet down groovy script in default config scripts when enabled
    set:
      JCasC:
        defaultConfig: true
        quietDown:
          enableScript: true
          quietDown: false
    asserts:
      - isNotNull:
          path: data.[jcasc-default-config-quiet-down.yaml]
      - matchSnapshot:
          path: data.[jcasc-default-config-quiet-down.yaml]
  - it: should include correct quietDown value
    set:
      JCasC:
        defaultConfig: true
        quietDown:
          enableScript: true
          quietDown: true
    asserts:
      - isNotNull:
          path: data.[jcasc-default-config-quiet-down.yaml]
      - matchSnapshot:
          path: data.[jcasc-default-config-quiet-down.yaml]
  - it: should apply the customised quiet down message if specified
    set:
      JCasC:
        defaultConfig: true
        quietDown:
          enableScript: true
          quietDown: true
          quietDownMessage: Custom quiet down message.
    asserts:
      - isNotNull:
          path: data.[jcasc-default-config-quiet-down.yaml]
      - matchSnapshot:
          path: data.[jcasc-default-config-quiet-down.yaml]
  - it: should not include quiet down groovy script in default config scripts when disabled
    set:
      JCasC:
        defaultConfig: true
        quietDown:
          enableScript: false
    asserts:
      - isNull:
          path: data.[jcasc-default-config-quiet-down.yaml]
