# This is not part of the Helm chart, it is used to build the image that will be referenced by the chart
apiVersion: template.openshift.io/v1
kind: Template
labels:
  # Naming - there is already a jenkins-master build config and image stream in the digital-image-builds namespace used
  # by jenkins-cd-ansible. So naming this build config and image stream jenkins-helm to make it obvious.
  template: jenkins-helm-build

parameters:
  - description: The base image kind
    displayName: Base image kind
    name: BASE_IMAGE_KIND
    value: 'ImageStreamTag'
  - description: The base image name
    displayName: Base image name
    name: BASE_IMAGE_NAME
    value: 'jenkins-ocp-anz'
  - description: The base image namespace
    displayName: Base image namespace
    name: BASE_IMAGE_NAMESPACE
    value: 'openshift'
  - description: The base image tag
    displayName: Base image tag
    name: BASE_IMAGE_TAG
    required: true
  - description: Name of the image to output the build to
    displayName: Output image name
    name: OUTPUT_IMAGE_NAME
    value: jenkins-helm
    required: false
  - description: Tag to be applied to the built image
    displayName: Output image tag
    name: OUTPUT_IMAGE_TAG
    required: true
  - description: base image digest
    name: BASE_IMAGE_DIGEST
    required: false
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: ${OUTPUT_IMAGE_NAME}

  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: ${OUTPUT_IMAGE_NAME}
    spec:
      runPolicy: Parallel
      nodeSelector: null
      resources:
        requests:
          cpu: "200m"
          memory: "500Mi"
        limits:
          cpu: "2"
          memory: "2Gi"
      output:
        to:
          kind: ImageStreamTag
          name: ${OUTPUT_IMAGE_NAME}:${OUTPUT_IMAGE_TAG}
        imageLabels:
          - name: nz.co.anz.base_image_digest
            value: ${BASE_IMAGE_DIGEST}
      postCommit: {}
      source:
        type: Binary
      strategy:
        sourceStrategy:
          env:
            - name: JENKINS_UC_DOWNLOAD
              value: https://artifactory-staging.nz.service.anz:443/artifactory/generic-jenkins-ci-virtual
          from:
            kind: ${BASE_IMAGE_KIND}
            name: ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}
            namespace: ${BASE_IMAGE_NAMESPACE}
        type: Source
