apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jenkins.jcascConfigMapName" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
data:
{{- if .Values.JCasC.defaultConfig }}
  {{- /* using a list to make adding new default config scripts easy */}}
  {{- range list "basic" "proxy" "clouds" "nodes" "env-vars" "script-approval" "bitbucket" "libraries" "slack" "vault" "openshift" "credentials" "openshift-sync" "quiet-down" "mailer" -}}
    {{- $scriptContent := (include (printf "jenkins.casc.defaults.%s" .) $) }}
    {{- if $scriptContent }}
      {{- /* only generate the config yaml file when is has content */}}
      {{- printf "jcasc-default-config-%s.yaml" . | nindent 2 }}: |-
      {{- $scriptContent | indent 4 }}
    {{- end }}
  {{- end }}
{{- end }}

{{- range $key, $val := .Values.JCasC.configScripts }}
  {{- if $val }}
  {{ $key }}.yaml: |-
    {{- tpl $val $ | nindent 4 }}
  {{- end }}
{{- end }}
