JCasC:
  configScripts:
    prod-jobs: |
      jobs:
        - script: |
            {{- .Files.Get "groovy-lib/pipeline-helper.groovy" | nindent 6 }}
            {{- tpl $.Values.pipelineTrigger $ | nindent 6 }}
            {{- tpl $.Values.nzdwProdPipeline $ | nindent 6 }}
            {{- tpl $.Values.nzdwProdDeploymentPipeline $ | nindent 6 }}
            {{- tpl $.Values.Add_Release_Tag_V3 $ | nindent 6 }}
            {{- tpl $.Values.Automated_branch_deletion $ | nindent 6 }}
            {{- tpl $.Values.NZDW_CONTROL_TBL_BKP $ | nindent 6 }}
            {{- tpl $.Values.teradataUdeployPipeline $ | nindent 6 }}
            {{- tpl $.Values.datastageUdeployPipeline $ | nindent 6 }}
            {{- tpl $.Values.prodPipelineTestingSuite1Job $ | nindent 6 }}
            {{- tpl $.Values.prodDeploymentPipelineTestingSuite1Job $ | nindent 6 }}
            {{- tpl $.Values.prodPipelineTestingSuite2Job $ | nindent 6 }}
            {{- tpl $.Values.prodDeploymentPipelineTestingSuite2Job $ | nindent 6 }}
            {{- tpl $.Values.prodPipelineTestingSuite3Job $ | nindent 6 }}
            {{- tpl $.Values.prodDeploymentPipelineTestingSuite3Job $ | nindent 6 }}
            {{- tpl $.Values.prodPipelineTestingSuite4Job $ | nindent 6 }}
            {{- tpl $.Values.prodDeploymentPipelineTestingSuite4Job $ | nindent 6 }}
            {{- tpl $.Values.bitbucketBranchUnlock $ | nindent 6 }}

pipelineTrigger: |
  bitbucketPipelineJob(
    jobName: "Pipeline_Trigger",
    gitUrl: "https://bitbucket.nz.service.anz/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "Jenkinsfile_PipelineTrigger",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "50",
    webhookTrigger: true,
    triggerGenericVariables: [
      [
        key: 'requestBody',
        value: '$',
        expressionType: 'JSONPath'
      ]
    ],
    triggerCredentialToken: 'bitBucketWebhookToken',
    triggerCause: 'BitBucket Pull Request Approved',
    triggerPrintPost: true,
    authorization: true,
    jobPerms: [
      [
        name: 'anonymous',
        type: 'user',
        permissions: [ 'Job/Read' ]
      ],
      [
        name: 'authenticated',
        type: 'group',
        permissions: [ 'Job/Read' ]
      ]
    ]
  )

Add_Release_Tag_V3: |
  bitbucketPipelineJob(
    jobName: "Add_Release_Tag_V3",
    gitUrl: "https://bitbucket.nz.service.anz/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "Jenkinsfile_add_release_tag_v3",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "100",
    authorization: true,
    webhookTrigger: true,
    triggerCredentialToken: 'autoTagWebhookToken',
    triggerCause: 'Generic Cause',
  )

Automated_branch_deletion: |
  bitbucketPipelineJob(
    jobName: "Automated_branch_deletion",
    description: "This job is used to purge a nzdw_repo branch after its PR is merged to integration (by the pipeline or manually). A BitBucket webhook fires this job with a 'pr merge' payload",
    gitUrl: "https://bitbucket.nz.service.anz/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "Jenkinsfile_Automated_branch_deletion",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "100",
    authorization: true,
    webhookTrigger: true,
    triggerCredentialToken: 'pr_merge',
    triggerCause: 'Generic Cause',
    triggerGenericVariables: [[key: 'requestBody', value: '$', expressionType: 'JSONPath']],
  )

NZDW_CONTROL_TBL_BKP: |
  bitbucketPipelineJob(
    jobName: "NZDW_CONTROL_TBL_BKP",
    gitUrl: "https://bitbucket.nz.service.anz/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "controlTable/Jenkinsfile",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "100",
    authorization: true,
    cronSpec: 'H 9 * * *',
  )

nzdwProdPipeline: |
  bitbucketPipelineJob(
    jobName: "NZDW - PROD Pipeline",
    gitUrl: "https://bitbucket.nz.service.anz/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "Jenkinsfile",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "100",
    parametersNeeded: true,
    stringParams: [
      [
        name: 'branch_name',
        description: 'Branch name to run i.e. SKYNET/DST-1234_short_description',
        trim: false
      ]
    ],
    authorization: true,
    jobPerms: [
      [
        name: 'anonymous',
        type: 'user',
        permissions: [ 'Job/Read' ]
      ],
      [
        name: 'authenticated',
        type: 'group',
        permissions: [ 'Job/Read' ]
      ],
      [
        name: 'Rg_Svc NZ Data Delivery - Jenkins Prod Pipeline Managers',
        type: 'group',
        permissions: [ 'Job/Read', 'Job/Cancel', 'Run/Replay' ]
      ]
    ]
  )

nzdwProdDeploymentPipeline: |
  bitbucketPipelineJob(
    jobName: "NZDW - PROD Deployment pipeline",
    gitUrl: "https://bitbucket.nz.service.anz/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "vars/Jenkins-datapipeline-deploy.groovy",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "300",
    parametersNeeded: true,
    stringParams: [
      [
        name: 'version', 
        desc: 'Artifactory version', 
      ],
      [
        name: 'Branch_name',
        desc: '',
      ],
      [
        name: 'ChangeRequestID',
        desc: '',
      ]
    ],
    choiceParams: [
      [
        name: 'EnvironmentToken',
        desc: 'Database environment to deploy to',
        options: [ 'SIT', 'OAT', 'PRD' ]
      ]
    ],
    booleanParams: [
      [
        name: 'TeradataDeploy',
        defaultValue: true,
        desc: 'Select/TRUE to deploy Teradata components'
      ],
      [
        name: 'DatastageUnixDeploy',
        defaultValue: true,
        desc: 'Select/TRUE to deploy Datastage components'
      ],
      [
        name: 'Dml2Deploy',
        defaultValue: false,
        desc: 'Select/TRUE to deploy DML2 components'
      ],
      [
        name: 'OracleDeploy',
        defaultValue: false,
        desc: 'Select/TRUE to deploy Oracle components'
      ],
      [
        name: 'ControlMDeploy',
        defaultValue: false,
        desc: ''
      ]
    ],
    authorization: true,
    jobPerms: [
      [
        name: 'anonymous',
        type: 'user',
        permissions: [ 'Job/Read' ]
      ],
      [
        name: 'authenticated',
        type: 'group',
        permissions: [ 'Job/Read' ]
      ]
    ]
  )

teradataUdeployPipeline: |
  bitbucketPipelineJob(
    jobName: "Teradata Alternative Pipeline",
    gitUrl: "https://bitbucket.nz.service.anz:443/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "udeploy/global/teradata/Jenkinsfile",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "100",
    parametersNeeded: true,
    authorization: true,
    jobPerms: [
      [
        name: 'anonymous',
        type: 'user',
        permissions: [ 'Job/Read' ]
      ],
      [
        name: 'authenticated',
        type: 'group',
        permissions: [ 'Job/Read' ]
      ],
      [
        name: 'ahmeda11',
        type: 'user',
        permissions: [
          'Job/Build',
          'Job/Cancel',
          'Job/Read'
        ]
      ],
      [
        name: 'jothikur',
        type: 'user',
        permissions: [
          'Job/Build',
          'Job/Cancel',
          'Job/Read'
        ]
      ],
      [
        name: 'jains50',
        type: 'user',
        permissions: [
          'Job/Build',
          'Job/Cancel',
          'Job/Read'
        ]
      ]
    ],
  )

datastageUdeployPipeline: |
  bitbucketPipelineJob(
    jobName: "DataStage Alternative Pipeline",
    gitUrl: "https://bitbucket.nz.service.anz:443/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "udeploy/global/datastage/Jenkinsfile",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "100",
    parametersNeeded: true,
    authorization: true,
    jobPerms: [
      [
        name: 'gaurm',
        type: 'user',
        permissions: [
          'Job/Build',
          'Job/Cancel',
          'Job/Read'
        ]
      ],
      [
        name: 'zhangm2',
        type: 'user',
        permissions: [
          'Job/Build',
          'Job/Cancel',
          'Job/Read'
        ]
      ]
    ],
  )

bitbucketBranchUnlock: |
  bitbucketPipelineJob(
    jobName: "BitBucket Branch Unlock",
    description: "This is a Proof of Concept (POC) job to unlock branches in BitBucket. This is not the final implementation.",
    gitUrl: "https://bitbucket.nz.service.anz/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "Jenkinsfile_Branch_Release",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "100",
    parametersNeeded: false,
    authorization: true,
  )

prodPipelineTestingSuite1Job: |
  bitbucketPipelineJob(
    jobName: "Testing Suite 1 - PROD Pipeline",
    gitUrl: "https://bitbucket.nz.service.anz:443/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "Jenkinsfile",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "10",
    parametersNeeded: true,
    stringParams: [
      [
        name: 'branch_name',
        desc: 'Branch name to run i.e. SKYNET/DST-1234_short_description',
        trim: false
      ]
    ],
    authorization: true,
  )

prodDeploymentPipelineTestingSuite1Job: |
  bitbucketPipelineJob(
    jobName: "Testing Suite 1 - PROD Deployment Pipeline",
    gitUrl: "https://bitbucket.nz.service.anz:443/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "vars/Jenkins-datapipeline-deploy.groovy",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "10",
    parametersNeeded: true,
    stringParams: [
      [
        name: 'version', 
        desc: 'Artifactory version'
      ],
      [
        name: 'Branch_name',
        desc: ''
      ],
      [
        name: 'ChangeRequestID',
        desc: ''
      ]
    ],
    choiceParams: [
      [
        name: 'EnvironmentToken',
        desc: 'Database environment to deploy to',
        options: [ 'SIT', 'OAT', 'PRD' ]
      ]
    ],
    booleanParams: [
      [
        name: 'TeradataDeploy',
        defaultValue: true,
        desc: 'Select/TRUE to deploy Teradata components'
      ],
      [
        name: 'DatastageUnixDeploy',
        defaultValue: true,
        desc: 'Select/TRUE to deploy Datastage components'
      ],
      [
        name: 'Dml2Deploy',
        defaultValue: false,
        desc: 'Select/TRUE to deploy DML2 components'
      ],
      [
        name: 'OracleDeploy',
        defaultValue: false,
        desc: 'Select/TRUE to deploy Oracle components'
      ],
      [
        name: 'ControlMDeploy',
        defaultValue: false,
        desc: ''
      ]
    ],
    authorization: true,
  )

prodPipelineTestingSuite2Job: |
  bitbucketPipelineJob(
    jobName: "Testing Suite 2 - PROD Pipeline",
    gitUrl: "https://bitbucket.nz.service.anz:443/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "Jenkinsfile",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "10",
    parametersNeeded: true,
    stringParams: [
      [
        name: 'branch_name',
        desc: 'Branch name to run i.e. SKYNET/DST-1234_short_description',
        trim: false
      ]
    ],
    authorization: true,
  )

prodDeploymentPipelineTestingSuite2Job: |
  bitbucketPipelineJob(
    jobName: "Testing Suite 2 - PROD Deployment Pipeline",
    gitUrl: "https://bitbucket.nz.service.anz:443/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "vars/Jenkins-datapipeline-deploy.groovy",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "10",
    parametersNeeded: true,
    stringParams: [
      [
        name: 'version', 
        desc: 'Artifactory version'
      ],
      [
        name: 'Branch_name',
        desc: ''
      ],
      [
        name: 'ChangeRequestID',
        desc: ''
      ]
    ],
    choiceParams: [
      [
        name: 'EnvironmentToken',
        desc: 'Database environment to deploy to',
        options: [ 'SIT', 'OAT', 'PRD' ]
      ]
    ],
    booleanParams: [
      [
        name: 'TeradataDeploy',
        defaultValue: true,
        desc: 'Select/TRUE to deploy Teradata components'
      ],
      [
        name: 'DatastageUnixDeploy',
        defaultValue: true,
        desc: 'Select/TRUE to deploy Datastage components'
      ],
      [
        name: 'Dml2Deploy',
        defaultValue: false,
        desc: 'Select/TRUE to deploy DML2 components'
      ],
      [
        name: 'OracleDeploy',
        defaultValue: false,
        desc: 'Select/TRUE to deploy Oracle components'
      ],
      [
        name: 'ControlMDeploy',
        defaultValue: false,
        desc: ''
      ]
    ],
    authorization: true,
  )

prodPipelineTestingSuite3Job: |
  bitbucketPipelineJob(
    jobName: "Testing Suite 3 - PROD Pipeline",
    gitUrl: "https://bitbucket.nz.service.anz:443/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "Jenkinsfile",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "10",
    parametersNeeded: true,
    stringParams: [
      [
        name: 'branch_name',
        desc: 'Branch name to run i.e. SKYNET/DST-1234_short_description',
        trim: false
      ]
    ],
    authorization: true,
  )

prodDeploymentPipelineTestingSuite3Job: |
  bitbucketPipelineJob(
    jobName: "Testing Suite 3 - PROD Deployment Pipeline",
    gitUrl: "https://bitbucket.nz.service.anz:443/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "vars/Jenkins-datapipeline-deploy.groovy",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "10",
    parametersNeeded: true,
    stringParams: [
      [
        name: 'version', 
        desc: 'Artifactory version'
      ],
      [
        name: 'Branch_name',
        desc: ''
      ],
      [
        name: 'ChangeRequestID',
        desc: ''
      ]
    ],
    choiceParams: [
      [
        name: 'EnvironmentToken',
        desc: 'Database environment to deploy to',
        options: [ 'SIT', 'OAT', 'PRD' ]
      ]
    ],
    booleanParams: [
      [
        name: 'TeradataDeploy',
        defaultValue: true,
        desc: 'Select/TRUE to deploy Teradata components'
      ],
      [
        name: 'DatastageUnixDeploy',
        defaultValue: true,
        desc: 'Select/TRUE to deploy Datastage components'
      ],
      [
        name: 'Dml2Deploy',
        defaultValue: false,
        desc: 'Select/TRUE to deploy DML2 components'
      ],
      [
        name: 'OracleDeploy',
        defaultValue: false,
        desc: 'Select/TRUE to deploy Oracle components'
      ],
      [
        name: 'ControlMDeploy',
        defaultValue: false,
        desc: ''
      ]
    ],
    authorization: true,
  )

prodPipelineTestingSuite4Job: |
  bitbucketPipelineJob(
    jobName: "Testing Suite 4 - PROD Pipeline",
    gitUrl: "https://bitbucket.nz.service.anz:443/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "Jenkinsfile",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "10",
    parametersNeeded: true,
    stringParams: [
      [
        name: 'branch_name',
        desc: 'Branch name to run i.e. SKYNET/DST-1234_short_description',
        trim: false
      ]
    ],
    authorization: true,
  )

prodDeploymentPipelineTestingSuite4Job: |
  bitbucketPipelineJob(
    jobName: "Testing Suite 4 - PROD Deployment Pipeline",
    gitUrl: "https://bitbucket.nz.service.anz:443/scm/dn/nzdw_build_utility.git",
    credentialsId: "bitBucketUsernamePasswordCredentials",
    branch: "master",
    scriptPath: "vars/Jenkins-datapipeline-deploy.groovy",
    triggerBuildOnPush: false,
    disableConcurBuilds: false,
    pollSCMSpec: false,
    buildRetentionNumStr: "10",
    parametersNeeded: true,
    stringParams: [
      [
        name: 'version', 
        desc: 'Artifactory version'
      ],
      [
        name: 'Branch_name',
        desc: ''
      ],
      [
        name: 'ChangeRequestID',
        desc: ''
      ]
    ],
    choiceParams: [
      [
        name: 'EnvironmentToken',
        desc: 'Database environment to deploy to',
        options: [ 'SIT', 'OAT', 'PRD' ]
      ]
    ],
    booleanParams: [
      [
        name: 'TeradataDeploy',
        defaultValue: true,
        desc: 'Select/TRUE to deploy Teradata components'
      ],
      [
        name: 'DatastageUnixDeploy',
        defaultValue: true,
        desc: 'Select/TRUE to deploy Datastage components'
      ],
      [
        name: 'Dml2Deploy',
        defaultValue: false,
        desc: 'Select/TRUE to deploy DML2 components'
      ],
      [
        name: 'OracleDeploy',
        defaultValue: false,
        desc: 'Select/TRUE to deploy Oracle components'
      ],
      [
        name: 'ControlMDeploy',
        defaultValue: false,
        desc: ''
      ]
    ],
    authorization: true,
  )