image:
  repository: "nzdd-jenkins-prod/jenkins-helm"

ssh:
    known_hosts: |
        nztih02v.nz.unix.test,10.106.215.96 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPyv2SHhwf+u5t4eXNiUqbs4A1zJVKuhsZsOfPuoDX9Eron5BDxOHg39/TBHZ3RbN5u84Uj5dd2BzQE/nGVScg0=
        nztih00v.nz.unix.test,10.106.184.131 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPyv2SHhwf+u5t4eXNiUqbs4A1zJVKuhsZsOfPuoDX9Eron5BDxOHg39/TBHZ3RbN5u84Uj5dd2BzQE/nGVScg0=
        nzqih02v.nz.unix.test,10.106.215.101 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPyv2SHhwf+u5t4eXNiUqbs4A1zJVKuhsZsOfPuoDX9Eron5BDxOHg39/TBHZ3RbN5u84Uj5dd2BzQE/nGVScg0=
        nzqih00v.nz.unix.test,10.106.184.129 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPyv2SHhwf+u5t4eXNiUqbs4A1zJVKuhsZsOfPuoDX9Eron5BDxOHg39/TBHZ3RbN5u84Uj5dd2BzQE/nGVScg0=
        nzpih00v.nz.unix.anz,10.105.207.90 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPyv2SHhwf+u5t4eXNiUqbs4A1zJVKuhsZsOfPuoDX9Eron5BDxOHg39/TBHZ3RbN5u84Uj5dd2BzQE/nGVScg0=
        nzpih02v.nz.unix.anz,10.105.207.15 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPyv2SHhwf+u5t4eXNiUqbs4A1zJVKuhsZsOfPuoDX9Eron5BDxOHg39/TBHZ3RbN5u84Uj5dd2BzQE/nGVScg0=
        bitbucket.nz.service.anz,10.105.210.55 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHipBy2SYqH6VyNsI/xUO/sL0z+r48QXXEzdY1c9qfXxqx/fdjtfkzwMO36jx7KtjmtpC0uR2IyI1DGxuO/3AWc=
        [bitbucket.nz.service.anz]:7998,[10.105.210.55]:7998 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmlCvbpWCrhvBZUxUD1NGyA45WGjVKQ18RclWrqUdSwk+QBi/XKdgBSinXl4kYnU+gRSiVSeNuhmHIFCq5klpxluaCZg2ywwEMdgEbW0TnJgIajno+/Kpa7IM3KPewVxlajuE4CO+1WDRMEK0ws3gFvl9368/nyGe8cTKK8MtG2gVpQUUcp+3/N21LAMzikNWdBqyagE83G5TRijNEjAgnJwa/w+l6KO16h7g9fYcsxESYuEhDhcutVaOYQO3I18zM2gWEHOpACczIpN9D8Vb4ErOysRr2j5AoqKzNwHCf4W00m5BxdjiJhyC6wWJBp7p2/JqVT5rZNCf+EAD7D+o3

JCasC:
  envVars:
    "TDDevelopment": "nztddev.unix.anznb.co.nz"
  
  # scriptApproval:
  #   - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods invokeMethod"
  #   - "java.lang.Object java.lang.String java.lang.Object"

  scriptApproval:
  - "method hudson.model.Run getCause java.lang.Class"
  - "method org.jenkinsci.plugins.workflow.support.steps.build.RunWrapper getRawBuild"
  - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods getProperties java.lang.Object"
  - "method java.io.File exists"
  - "method java.io.File getName"
  - "method java.io.File getPath"
  - "method java.io.File isDirectory"
  - "method java.io.File lastModified"
  - "method java.io.File listFiles"
  - "new java.io.File java.lang.String"
  - "new hudson.util.VersionNumber java.lang.String"
  - "method hudson.util.VersionNumber isNewerThanOrEqualTo hudson.util.VersionNumber"
  
  configScripts:
    jenkins-permissions: |
      jenkins:
        authorizationStrategy:
          projectMatrix:
            entries:
            - group:
                name: "Rg_Svc NZ Data Analytics Openshift Project Admins"
                permissions:
                - "Overall/Administer"
            - group:
                name: "Rg_Svc NZ Data Analytics Openshift Project Developers"
                permissions:
                - "Overall/Read"
            - group:
                name: "Rg_Svc NZ Data Delivery - Jenkins Admins"
                permissions:
                - "Overall/Administer"
            - group:
                name: "Rg_Svc NZ Data Delivery - Jenkins Prod Pipeline Managers"
                permissions:
                - "Overall/Read"
            - user:
                name: "anonymous"
                permissions:
                - "Overall/Read"
            - user:
                name: "hazlehuj"
                permissions:
                - "Overall/Administer"
  
    # Configures the views set on Jenkins Dashboard
    set-custom-views: |
      jenkins:
        views:
        - list:
            name: "PROD Pipeline"
            columns:
            {{- range .Values.nzdd.defaultColumns }}
            - {{ . }}
            {{- end }}
            description: "# PROD Pipelines"
            jobNames:
            - "Add_Release_Tag_V3"
            - "Automated_branch_deletion"
            - "BitBucket Branch Unlock"
            - "NZDW - PROD Deployment pipeline"
            - "NZDW - PROD Pipeline"
            - "NZDW_CONTROL_TBL_BKP"
            - "Pipeline_Trigger"
        - list:
            name: "Manual Deployment"
            columns:
            {{- range .Values.nzdd.defaultColumns }}
            - {{ . }}
            {{- end }}
            description: "# Alternative Deployment Mechanisms for Teradata and DataStage"
            jobNames:
            - "Teradata Alternative Pipeline"
            - "DataStage Alternative Pipeline"
        - list:
            name: "Testing Suite"
            columns:
            {{- range .Values.nzdd.defaultColumns }}
            - {{ . }}
            {{- end }}
            description: "# Testing Suite"
            jobNames:
            - "Testing Suite 1 - PROD Pipeline"
            - "Testing Suite 1 - PROD Deployment Pipeline"
            - "Testing Suite 2 - PROD Pipeline"
            - "Testing Suite 2 - PROD Deployment Pipeline"
            - "Testing Suite 3 - PROD Pipeline"
            - "Testing Suite 3 - PROD Deployment Pipeline"
            - "Testing Suite 4 - PROD Pipeline"
            - "Testing Suite 4 - PROD Deployment Pipeline"
          
    header-theme: |
      appearance:
        customHeader:
          enabled: true
          header: "logo"
          headerColor:
            backgroundColor: "{{ .Values.nzdd.header.backgroundColour }}"
            color: "{{ .Values.nzdd.header.textColour }}"
            hoverColor: "{{ .Values.nzdd.header.hoverColour }}"
          logo:
            symbol:
              symbol: "symbol-jenkins"
          logoText: "{{ .Values.nzdd.header.logoText }}"
          thinHeader: false
          title: "{{ .Values.nzdd.header.titleText }}"

    database-plugin: |
      unclassified:
        globalDatabaseConfiguration:
          database:
            generic:
              driver: "{{ .Values.nzdd.databasePlugin.driver }}"
              url: "{{ .Values.nzdd.databasePlugin.url }}"
              username: "{{ .Values.nzdd.databasePlugin.username }}"
              password: "{{ .Values.nzdd.databasePlugin.password }}"

    disable-admin-monitors: |
        jenkins:
          disabledAdministrativeMonitors:
          - "jenkins.security.csrf.CSRFAdministrativeMonitor"
          - "org.jenkinsci.plugins.matrixauth.AmbiguityMonitor"
          - "hudson.model.UpdateCenter$CoreUpdateMonitor"
          - "hudson.diagnosis.TooManyJobsButNoView"
          - "jenkins.model.BuiltInNodeMigration"
          - "jenkins.security.QueueItemAuthenticatorMonitor"
          - "hudson.PluginManager$PluginDeprecationMonitor"
          - "jenkins.security.ResourceDomainRecommendation"
          - "jenkins.diagnostics.ControllerExecutorsAgents"
          - "jenkins.security.s2m.MasterKillSwitchWarning"

    lockable-resources: |
      unclassified:
        lockableResourcesManager:
          declaredResources:
            - name: LockA
              labels: LockA
              description: Lock Deployment and testing stages so they cannot run concurrently
            - name: Acceptance
              labels: Acceptance
              description: Lock Deployment and testing stages so they cannot run concurrently
            - name: Union
              labels: Union
              description: Lock Deployment and testing stages so they cannot run concurrently
            - name: Rehearsal
              labels: Rehearsal
              description: Lock Deployment and testing stages so they cannot run concurrently
            - name: Production
              labels: Production
              description: Lock Deployment and testing stages so they cannot run concurrently
            - name: lock-processingtags
              labels: lock-processingtags
              description: Lock Deployment and testing stages so they cannot run concurrently

    # Configure the default shell binary.
    set-bash-shell: |
      unclassified:
        shell:
          shell: /usr/bin/bash

    # Configure build concurrency settings.
    set-build-concurrency: |
      unclassified:
          throttleJobProperty:
            categories:
            - categoryName: "ThrottleA"
              maxConcurrentPerNode: 0
              maxConcurrentTotal: 10

    # Select Markdown as the default format for text fields in the UI.
    set-markup-formatter: |
      jenkins:
        markupFormatter: "markdownFormatter"
        # Could also use SafeHTML instead if required.
        markupFormatter:
          rawHtml:
            disableSyntaxHighlighting: false
        # Or just plain text (default)
        # markupFormatter: "plainText"

    # Configure the folder health metrics plugin.
    bubble-up-child-health-metrics: |
      unclassified:
        defaultFolderConfiguration:
          healthMetrics:
          - worstChildHealthMetric:
              recursive: true