persistentVolume:
  storage: 50Gi

buildBranchRegex: "master"

JCasC:
  openshiftClouds:
    prod:
      serverUrl: "" # to be set by prod-cs1.yaml and prod-cs2.yaml
      namespace: "{{ .Release.Namespace }}"
      webSocket: true
      defaultsProviderTemplate: "default-jenkins-slave"
      simpleTemplates:
        templates:
          default-jenkins-slave:
            label: "prod"
            image:
              registry: ""
            useGoInit: true
            idleMinutes: ""
            envVars:
              kubernetes_backend: "{{ $.Values.JCasC.vault.mountPath }}"      
              
  pipelineLibraries:
    openshiftPipeline:
      repo: https://bitbucket.nz.service.anz/scm/pipe/openshift-pipeline.git
      credentialsId: bitbucket

  permanentNodes:
    enabled: true
    commonAttributes:
      numExecutors: 5
      retentionStrategy: "always"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
    agents:
      APPNZ301AKL0746:
        host: "APPNZ301AKL0746.globaltest.anz.com"
        labelString: "opal-builder"
        nodeDescription: "Windows agent to build OPAL"

  configScripts:
    multibranch-pipeline-jobs: |
      jobs:
        - script: |
            {{- .Files.Get "groovy-lib/organization-folder-helper.groovy" | nindent 6 }}
            bitbucketOrganizationFolder(
              folderName: "OPAL",
              displayName: "OPAL",
              project: "OPAL",
              repoRegex: ".*",
              credentialsId: 'bitbucket',
              branchRegex: 'master',
              pullRequestDiscoveryStrategyId: 1,
              branchNamesToBuildAutomaticallyRegex: ""
            )
