persistentVolume:
  storage: 50Gi

JCasC:
  openshiftClouds:
    openshift_production:
      serverUrl: "" # to be set by prod-cs1.yaml and prod-cs2.yaml
      namespace: "bwb"
      webSocket: true
    # explicit cloud definition for the 2 prod clusters
    openshift_cs1_prod:
      serverUrl: "https://api.cs1.nz.service.anz:6443"
      namespace: "{{ .Release.Namespace }}"
      credentialsId: "cs1-prod-openshift"
      skipTlsVerify: false
      webSocket: true
    openshift_cs2_prod:
      serverUrl: "https://api.cs2.nz.service.anz:6443"
      namespace: "{{ .Release.Namespace }}"
      credentialsId: "cs2-prod-openshift"
      skipTlsVerify: false
      webSocket: true

  # Windows slave configuration
  permanentNodes:
    enabled: true
    commonAttributes:
      mode: EXCLUSIVE
      numExecutors: 5
      retentionStrategy: "always"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
    agents:
      APPNZ301AKL0732:
        host: "APPNZ301AKL0732.globaltest.anz.com"
        labelString: "Windows"
        nodeDescription: "windows slave to run journey tests"

  configScripts: # To change buildBranchRegex to master once we're ready
    multi-branch-jobs: |
      jobs:
        - script: |
            {{- .Files.Get "groovy-lib/organization-folder-helper.groovy" | nindent 6 }}

            def buildBranchRegex = 'master'
            def displayNameSuffix = 'Master Branch'
            {{- tpl $.Values.OMLibsJobsSnippet $ | nindent 6 }}

            {{- tpl $.Values.OMJobsSnippet $ | nindent 6 }}
