JCasC:
  vault:
    credentials:
      # OpenShift credentials
      ocp3-prod-openshift:
        kind: vaultStringCredentialImpl
        description: "OpenShift service account token for OCP3 prod cluster"
        path: 'secret/context/{{ .Release.Namespace }}/{{ include "jenkins.serviceAccountName" . }}/credentials/openshift-service-account'
        scope: GLOBAL
        vaultKey: "ocp3-prod-openshift"
      cs1-prod-openshift: # to be loaded to vault
        kind: vaultStringCredentialImpl
        description: "The 'jenkins' service account JWT from OCP4 cs1-prod for Kubernetes plugin"
        path: 'secret/context/{{ .Release.Namespace }}/{{ include "jenkins.serviceAccountName" .
        }}/credentials/openshift-service-account'
        scope: GLOBAL
        vaultKey: "cs1-prod-openshift"
      cs2-prod-openshift: # to be loaded to vault
        kind: vaultStringCredentialImpl
        description: "The 'jenkins' service account JWT from OCP4 cs2-prod for Kubernetes plugin"
        path: 'secret/context/{{ .Release.Namespace }}/{{ include "jenkins.serviceAccountName" .
        }}/credentials/openshift-service-account'
        scope: GLOBAL
        vaultKey: "cs2-prod-openshift"

      # credentials for OpenShift image registry
      non-production_bwb-ci_serviceaccount:
        kind: vaultUsernamePasswordCredentialImpl
        description: "OpenShift service account username and token for OCP3 non-prod cluster, used by openshift-pipeline to copy image from non-prod OpenShift image registry to prod"
        path: 'secret/context/{{ .Release.Namespace }}/{{ include "jenkins.serviceAccountName" . }}/credentials/openshift-service-account'
        scope: GLOBAL
        usernameKey: "username"
        passwordKey: "ocp3-dev-openshift"

      production_bwb_serviceaccount:
        kind: vaultUsernamePasswordCredentialImpl
        description: "OpenShift service account username and token for OCP3 prod cluster, used by openshift-pipeline to copy image from non-prod OpenShift image registry to prod"
        path: 'secret/context/{{ .Release.Namespace }}/{{ include "jenkins.serviceAccountName" . }}/credentials/openshift-service-account'
        scope: GLOBAL
        usernameKey: "username"
        passwordKey: "ocp3-prod-openshift"

      # Dynatrace credentials
      dynatrace-prod-api-key:
        kind: vaultStringCredentialImpl
        description: "API key for Dynatrace Production"
        path: 'secret/context/{{ .Release.Namespace }}/{{ include "jenkins.serviceAccountName" .
        }}/credentials/dynatrace'
        scope: GLOBAL
        vaultKey: "prod-token"

      # Oracle credentials
      oracle-automation-prod:
        kind: vaultUsernamePasswordCredentialImpl
        description: "Credentials for Oracle Production instance for automation"
        path: 'secret/context/{{ .Release.Namespace }}/{{ include "jenkins.serviceAccountName" .
        }}/credentials/oracle-provisioning'
        scope: GLOBAL
        usernameKey: "prod_username"
        passwordKey: "prod_password"

      # BWB Core MSSQL credentials
      database-automation-bwb-prod:
        kind: vaultUsernamePasswordCredentialImpl
        description: "Credentials for BWB Core Production Automation Database"
        path: 'secret/context/{{ .Release.Namespace }}/{{ include "jenkins.serviceAccountName" .
        }}/credentials/database-automation/bwb'
        scope: GLOBAL
        usernameKey: "prod_username"
        passwordKey: "prod_password"

      # BDP Deals Service MSSQL credentials
      database-automation-deals-service-prod:
        kind: vaultUsernamePasswordCredentialImpl
        description: "Credentials for Pricing Deals Service Production Automation Database"
        path:
          'secret/context/{{ .Release.Namespace }}/{{ include "jenkins.serviceAccountName" .
          }}/credentials/database-automation/deals-service'
        scope: GLOBAL
        usernameKey: "prod_username"
        passwordKey: "prod_password"

      # BDP Interest Rates Service MSSQL credentials
      database-automation-interest-rates-service-prod:
        kind: vaultUsernamePasswordCredentialImpl
        description: "Credentials for Pricing Interest Rates Service Production Automation Database"
        path:
          'secret/context/{{ .Release.Namespace }}/{{ include "jenkins.serviceAccountName" .
          }}/credentials/database-automation/deals-service'
        scope: GLOBAL
        usernameKey: "prod_username"
        passwordKey: "prod_password"

      # BDP Interest Rates Draft Service MSSQL credentials
      database-automation-rates-draft-service-prod:
        kind: vaultUsernamePasswordCredentialImpl
        description: "Credentials for Pricing Interest Rates Draft Service Production Automation Database"
        path:
          'secret/context/{{ .Release.Namespace }}/{{ include "jenkins.serviceAccountName" .
          }}/credentials/database-automation/rates-draft-service'
        scope: GLOBAL
        usernameKey: "prod_username"
        passwordKey: "prod_password"

      # BWB Loans Service MSSQL credentials
      database-automation-loans-prod:
        kind: vaultUsernamePasswordCredentialImpl
        description: "Credentials for Loans Service Production Automation Database"
        path:
          'secret/context/{{ .Release.Namespace }}/{{ include "jenkins.serviceAccountName" .
          }}/credentials/database-automation/loans'
        scope: GLOBAL
        usernameKey: 'prod_username'
        passwordKey: 'prod_password'
