persistentVolume:
  storage: 50Gi
  
resources:
  limits:
    memory: 8Gi
    cpu: 4

jenkins_java_overrides: -Dmail.smtp.starttls.enable=true -Dmail.smtp.ssl.trust=smtp.anz.co.nz

JCasC:
  vault:
    vaultUrl: "https://vault.nzlb.service.anz:8200"

  # Set to configure SlackNotifier plugin
  slackNotifier:
    credentialId: slack

  openshiftClouds:
    openshift_production:
      serverUrl: "https://caas-master.nzlb.service.anz:8443/"
      namespace: "sf-tools"
      credentialsId: "ocp3-prod-openshift"
      skipTlsVerify: false
      webSocket: true
    # explicit cloud definition for the 2 prod clusters
    openshift_cs1_prod:
      serverUrl: "https://api.cs1.nz.service.anz:6443"
      namespace: "sf-tools"
      credentialsId: "cs1-prod-openshift"
      skipTlsVerify: false
      webSocket: true

    openshift_cs2_prod:
      serverUrl: "https://api.cs2.nz.service.anz:6443"
      namespace: "sf-tools"
      credentialsId: "cs2-prod-openshift"
      skipTlsVerify: false
      webSocket: true
  configScripts:
    multi-branch-jobs: |
      jobs:
        - script: |
            {{- .Files.Get "groovy-lib/organization-folder-helper.groovy" | nindent 6 }}
            def buildBranchRegex = '.*-trunk|master|master-staging|train|ohana|price-engine-p3|customer-onboarding-p2|(term-deposit((-servicing)|(-pricing)|(-view))?)|credit-card|kiwisaver|contact-centre-app|must-chat|ocdd|no-advice|kyc-refresh|banks-r-us|ideqa'
            def displayNameSuffix = 'Master Branches'
            def buildRepoRegex = '.*'
            {{- tpl $.Values.SalesforceJobsSnippet $ | nindent 6 }}
            buildBranchRegex = 'master'
            buildRepoRegex = '^(?!openshift-pipeline$).*'
            {{- tpl $.Values.PipelineJobsSnippet $ | nindent 6 }}

mailer:
  smtpHost: smtp.anz.co.nz
  smtpPort: 25
