JCasC:
  quietDown:
    # cs2 cluster contains the backup instance, in quiet down mode by default
    quietDown: true
  openshiftClouds:
    openshift_cs2_dev:
      serverUrl: "https://api.cs2-dev.nz.service.test:6443"
      credentialsId: "ocp4-cs2-non-prod-openshift"  
    openshift_cs2_prod:
      serverUrl: "https://api.cs2.nz.service.anz:6443"
      credentialsId: "ocp4-cs2-prod-openshift"