JCasC:
  quietDown:
    quietDown: true

  openshiftClouds:
    nonprod:
      serverUrl: "https://api.cs2-dev.nz.service.test:6443"
      credentialsId: "openshift-cs2-dev"
    prod:
      serverUrl: "https://api.cs2.nz.service.anz:6443"
      credentialsId: "openshift-cs2"
