JCasC:
  quietDown:
    # cs2 cluster contains the backup instance, in quiet down mode by default
    quietDown: true

  openshiftClouds:
    openshift_non_prod:
      serverUrl: "https://api.cs2.nz.service.anz:6443"
      namespace: "{{ .Release.Namespace }}"
      webSocket: true

  permanentNodes:
    commonAttributes:
      remoteFS: "D:\\OLSWorkspaceCS2"