JCasC:
  permanentNodes:
    enabled: true
    commonAttributes:
      numExecutors: 1
      retentionStrategy: "always"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
    agents:
      APPNZ301AKL0746:
        host: "APPNZ301AKL0746.globaltest.anz.com"
        labelString: "ols-prod-builder sdp-prod-builder"
        nodeDescription: "Windows agent to build OnlineStore and SDP master branch pipeline"

  envVars:
      ARTIFACTORY_REPOSITORY_BASE_URL: https://artifactory.nz.service.anz/artifactory
      ARTIFACTORY_REPOSITORY_ID: generic-digital-sales-local

  configScripts:
    multibranch-pipeline-jobs: |
      jobs:
        - script: |
            {{- .Files.Get "groovy-lib/organization-folder-helper.groovy" | nindent 6 }}
            def buildBranchRegex = 'master'
            {{- tpl $.Values.DigitalSalesMasterSnippet $ | nindent 6 }}
