JCasC:
  openshiftClouds:
    openshift_non_prod:
      serverUrl: "https://api.cs1.nz.service.anz:6443"
      namespace: "{{ .Release.Namespace }}"
      webSocket: true

  permanentNodes:
    commonAttributes:
      remoteFS: "D:\\OLSWorkspaceCS1"