JCasC:
  vault:
    credentials:
      # OpenShift credentials
      cs1-prod-openshift: # to be loaded to vault
        kind: vaultStringCredentialImpl
        description: "The 'jenkins' service account JWT from OCP4 cs1-prod for Kubernetes plugin"
        path: 'secret/context/{{ .Release.Namespace }}/{{ include "jenkins.serviceAccountName" . }}/credentials/openshift-service-account'
        scope: GLOBAL
        vaultKey: "cs1-prod-openshift"
      cs2-prod-openshift: # to be loaded to vault
        kind: vaultStringCredentialImpl
        description: "The 'jenkins' service account JWT from OCP4 cs2-prod for Kubernetes plugin"
        path: 'secret/context/{{ .Release.Namespace }}/{{ include "jenkins.serviceAccountName" . }}/credentials/openshift-service-account'
        scope: GLOBAL
        vaultKey: "cs2-prod-openshift"

      # Dynatrace credentials
      dynatrace-prod-api-key:
        kind: vaultStringCredentialImpl
        description: "API key for Dynatrace Production"
        path: 'secret/context/{{ .Release.Namespace }}/{{ include "jenkins.serviceAccountName" . }}/credentials/dynatrace'
        scope: GLOBAL
        vaultKey: "prod-token"
