persistentVolume:
  storage: 50Gi

buildBranchRegex: "master"

JCasC:
  master:
    proxy:
      name: "nzswg-app.nz.service.anz"
      port: 80
      noProxyHost: |-
        *.service.dev
        *.test
        *.anz
        *.anznb.co.nz

  # Set to configure SlackNotifier plugin
  slackNotifier:
    credentialId: slack

  openshiftClouds:

    # OCP4 2 prod clusters
    openshift_cs1_prod:
      serverUrl: "https://api.cs1.nz.service.anz:6443"
      namespace: "csp-production"
      credentialsId: "cs1-prod-openshift"
      skipTlsVerify: false
      webSocket: true

    openshift_cs2_prod:
      serverUrl: "https://api.cs2.nz.service.anz:6443"
      namespace: "csp-production"
      credentialsId: "cs2-prod-openshift"
      skipTlsVerify: false
      webSocket: true

  configScripts:
    multi-branch-jobs: |
      jobs:
        - script: |
            {{- .Files.Get "groovy-lib/organization-folder-helper.groovy" | nindent 6 }}

            def buildBranchRegex = 'master'
            def displayNameSuffix = 'Master Branch'
            def buildRepoRegex = '^(?!transactions-container$|transactions-spring-boot$|digital-configuration$|pacman$|preauth$|wis$).*'
            {{- tpl $.Values.DigitalJobsSnippet $ | nindent 6 }}

            buildRepoRegex = '^(?!salesforce-pipeline$).*'
            {{- tpl $.Values.PipelineJobsSnippet $ | nindent 6 }}

            buildRepoRegex = '.*'
            {{- tpl $.Values.TriviaJobsSnippet $ | nindent 6 }}
            {{- tpl $.Values.CSPJobsSnippet $ | nindent 6 }}
            {{- tpl $.Values.ChannelMicroservicesJobsSnippet $ | nindent 6 }}
