persistentVolume:
  storage: 180Gi

jobsBackupRepository: "https://bitbucket.nz.service.anz/scm/GOM/jenkinsjobs-production.git"
jobsBackupRepositoryBranch: "master"

JCasC:
  openshiftClouds:
    openshift_prod:
      namespace: "{{ .Release.Namespace }}"
      skipTlsVerify: false
      webSocket: true