# The config that is common across both prod clusters
JCasC:
  vault:
    credentials:
      jenkins-ssh-from-slaves-to-oat-app-servers:
        kind: vaultSSHUserPrivateKeyImpl
        description: "Credentials for SSH access from the Jenkins slaves to the OAT app servers."
        path: '{{ tpl .Values.secretPathRoot $ }}/jenkins-ssh-from-slaves-to-oat-app-servers'
        scope: GLOBAL
      jenkins-ssh-from-slaves-to-oat-iis-servers:
        kind: vaultSSHUserPrivateKeyImpl
        description: "Credentials for SSH access from the Jenkins slaves to the OAT IIS web servers."
        path: '{{ tpl .Values.secretPathRoot $ }}/jenkins-ssh-from-slaves-to-oat-iis-servers'
        scope: GLOBAL
      jenkins-ssh-from-slaves-to-prod-app-servers:
        kind: vaultSSHUserPrivateKeyImpl
        description: "Credentials for SSH access from the Jenkins slaves to the Prod app servers."
        path: '{{ tpl .Values.secretPathRoot $ }}/jenkins-ssh-from-slaves-to-prod-app-servers'
        scope: GLOBAL
      jenkins-ssh-from-slaves-to-prod-iis-servers:
        kind: vaultSSHUserPrivateKeyImpl
        description: "Credentials for SSH access from the Jenkins slaves to the Prod IIS web servers."
        path: '{{ tpl .Values.secretPathRoot $ }}/jenkins-ssh-from-slaves-to-prod-iis-servers'
        scope: GLOBAL
      jenkins-as-nzadocicddsa:
        kind: vaultUsernamePasswordCredentialImpl
        description: "Credentials for Prod vDirect traffic management."
        path: '{{ tpl .Values.secretPathRoot $ }}/jenkins-as-nzadocicddsa'
        scope: GLOBAL
  # Set an environment variable on the slave. Used by the pipeline scripts to determine which app region configuration to load (Dev/Test1/2/3 vs OAT/Prod)
  envVars:
    OPENSHIFT_ENVIRONMENT: "prod"
  # Slave config. The remoteFS values are defined in the cluster specific config.
  permanentNodes:
    enabled: true
    commonAttributes:
      mode: NORMAL
      numExecutors: 20
      retentionStrategy: "always"
    agents:
      nzpit40v:
        host: "nzpit40v.nz.unix.anz"
        credentialsId: "jenkins-ssh-to-slaves"
        labelString: "slave"
        javaPath: "/app/jenkins/java/current/bin/java"
        hostKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDW+k3rKfZVR4rQEftvBurFOQzIToEkvgGvPuzKQt4H77KQMNyrTZt5TMBnBlL+1l7sYojiz3KT81b74uxEjCRYwAkkpRs7d4un0RAuRfzkq2lBCJD5E3Cy5EsAb+YL7KiDMrorrm+dofC5jSY7i1MG1LnlnW5+9RO5fOn9yuJcbdsAX9x7LXPAIHpYc9KXt/Kq3DwfLAZMSBEu4sKavxORMhbmWoPk1Cc2H7l5FNHWNogbyq6bjgB/hxQT05TdxPUhKNrlKFzmIeVdC2A9u8IQzgnZAWgZCRgQW3EdgfsUriKfNboMyka02rU9bnAx+kmTgmJEgJsMMtJt+fqcRHUp"
      nzpit41v:
        host: "nzpit41v.nz.unix.anz"
        credentialsId: "jenkins-ssh-to-slaves"
        labelString: "slave"
        javaPath: "/app/jenkins/java/current/bin/java"
        hostKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDW+k3rKfZVR4rQEftvBurFOQzIToEkvgGvPuzKQt4H77KQMNyrTZt5TMBnBlL+1l7sYojiz3KT81b74uxEjCRYwAkkpRs7d4un0RAuRfzkq2lBCJD5E3Cy5EsAb+YL7KiDMrorrm+dofC5jSY7i1MG1LnlnW5+9RO5fOn9yuJcbdsAX9x7LXPAIHpYc9KXt/Kq3DwfLAZMSBEu4sKavxORMhbmWoPk1Cc2H7l5FNHWNogbyq6bjgB/hxQT05TdxPUhKNrlKFzmIeVdC2A9u8IQzgnZAWgZCRgQW3EdgfsUriKfNboMyka02rU9bnAx+kmTgmJEgJsMMtJt+fqcRHUp"
