templates:
  - config-role-mapping.yaml
tests:
  - it: by default should not generate config map
    asserts:
      - hasDocuments:
          count: 0
  - it: when enabled, content should match snapshot
    set:
      customiseRoleMapping:
        enabled: true
    asserts:
      - hasDocuments:
          count: 1
      - equal:
          path: data.Overall-Administer
          value: admin
      - equal:
          path: data.Job-Build
          value: edit,admin
      - matchSnapshot: {}
  - it: should reflect the customisations made
    set:
      customiseRoleMapping:
        enabled: true
        mappings:
          Overall-Administer: edit,admin
          Job-Build: view,edit,admin
    asserts:
      - hasDocuments:
          count: 1
      - equal:
          path: data.Overall-Administer
          value: edit,admin
      - equal:
          path: data.Job-Build
          value: view,edit,admin
