templates:
  - config-jcasc.yaml
tests:
  - it: default JCasC should have no data
    asserts:
      - isNull:
          path: data
  - it: should process custom configScripts
    set:
      JCasC:
        configScripts:
          jenkins-global: |
            jenkins:
              systemMessage: This Jenkins is configured and managed 'as code'.
              mode: EXCLUSIVE
              numExecutors: 0
          init-scripts: |
            groovy:
              - script: >
                  println("This is Groovy script!");
    asserts:
      - matchSnapshot:
          path: data
  - it: should generate blank default config script when enabled
    set:
      domain: dummy.domain
      JCasC:
        defaultConfig: true
    asserts:
      - matchSnapshot:
          path: data
