templates:
  - persistentvolume.yaml
tests:
  - it: default manifest should match snapshot
    asserts:
      - matchSnapshot: {}
  - it: storage request should match snapshot
    set:
      persistentVolume:
        storage: 31Gi
    asserts:
      - equal:
          path: spec.resources.requests.storage
          value: 31Gi
  - it: single additional volume should match snapshot
    set:
      persistentVolume:
        storage: 7Gi
        additionalVolumes:
          - name: gitref-volume
            storage: 2Gi
            accessMode: ReadOnlyMany
    asserts:
      - hasDocuments:
          count: 2
      - matchSnapshot: {}
  - it: multiple additional volumes should match snapshot
    set:
      persistentVolume:
        storage: 7Gi
        additionalVolumes:
          - name: gitref-volume
            storage: 2Gi
            accessMode: ReadOnlyMany
          - name: maven-volume
            storage: 3Gi
            accessMode: ReadWriteMany
    asserts:
      - hasDocuments:
          count: 3
      - matchSnapshot: {}
  - it: "Should match snapshot when 'preventUninstall' is true for persistentVolume"
    set:
      persistentVolume:
        preventUninstall: true
    asserts:
      - matchSnapshot: {}
  - it: "Should match snapshot when 'preventUninstall' is true for one additional volume"
    set:
      persistentVolume:
        storage: 7Gi
        additionalVolumes:
          - name: gitref-volume
            storage: 2Gi
            accessMode: ReadOnlyMany
            preventUninstall: true
    asserts:
      - matchSnapshot: {}
  - it: "Should match snapshot when 'preventUninstall' is false for one additional volume"
    set:
      persistentVolume:
        storage: 7Gi
        additionalVolumes:
          - name: maven-volume
            storage: 3Gi
            accessMode: ReadWriteMany
            preventUninstall: false
    asserts:
      - matchSnapshot: {}
  - it: "Should match snapshot when 'preventUninstall' is set on multiple additional volumes"
    set:
      persistentVolume:
        storage: 7Gi
        additionalVolumes:
          - name: maven-volume
            storage: 3Gi
            accessMode: ReadWriteMany
            preventUninstall: true
          - name: gitref-volume
            storage: 3Gi
            accessMode: ReadWriteMany
    asserts:
      - matchSnapshot: {}