templates:
  - route.yaml
tests:
  - it: manifest should match snapshot
    set:
      domain: dummy.domain
    asserts:
      - matchSnapshot: {}
  - it: should include specified route annotations
    set:
      routeAnnotations:
        key1: value1
        key2: value2
    asserts:
      - matchSnapshot:
          path: metadata.annotations
  - it: should allow setting a completely custom route host
    set:
      domain: dummy.domain
      route:
        host: my.custom.domain
    asserts:
      - equal:
          path: spec.host
          value: my.custom.domain
  - it: should allow route host to be set without domain specified
    set:
      route:
        host: my.custom.domain
    asserts:
      - equal:
          path: spec.host
          value: my.custom.domain
  - it: should compute a route host using domain and subdomain
    set:
      domain: dummy.domain
      route:
        subDomain: subdomain
    asserts:
      - equal:
          path: spec.host
          value: subdomain.dummy.domain
  - it: should generate a full route host when not explicitly specified
    set:
      domain: dummy.domain
    asserts:
      - equal:
          path: spec.host
          value: RELEASE-NAME-jenkins-NAMESPACE.dummy.domain
  - it: full custom route should take precidence over subdomain route when both are specified
    set:
      domain: dummy.domain
      route:
        host: my.custom.domain
        subDomain: subdomain
    asserts:
      - equal: 
          path: spec.host
          value: my.custom.domain