persistentVolume:
  storage: 50Gi

JCasC:
  # Set to configure SlackNotifier plugin
  slackNotifier:
    credentialId: slack

  openshiftClouds:
    openshift_production:
      serverUrl: "" # to be set by prod-cs1.yaml and prod-cs2.yaml
      namespace: "digital-image-builds"
      credentialsId: "" # to be set by individual variants prod-cs1.yaml or prod-cs2.yaml
      skipTlsVerify: false
      webSocket: true

  configScripts:
    multi-branch-jobs: |
      jobs:
        - script: |
            {{- .Files.Get "groovy-lib/organization-folder-helper.groovy" | nindent 6 }}

            def buildBranchRegex = 'master'
            {{- tpl $.Values.DigitalImagesJobsSnippet $ | nindent 6 }}